POST http://localhost:3000/protected HTTP/1.1
Authorization: Bearer eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJlbWFpbCI6ImNoaW5ndXllbl90ZXN0MTJAZmxvbWFpbC5uZXQiLCJpYXQiOjE3MDI0NTYwMTQsImV4cCI6MTcwMjQ1NjMxNH0.nEob96TCV2AOqFPV3jhjcabRIePxY7xxexBF5Syzh5S73rhp08HxuLineBjen9Xcj31EBWTGmu9Hfoylo--iotYH5ZlGgi_KltwY-Slw6KxqmDDuuUgzUh6VSlMYT4aqw5JxadHKv5-IfXGiQzlbZ5dj55rPNUpf3aescFTEoSDO5AqhB4zaQXItTxb7ZnWSWQ3ROTVT1SD0JTvCH7XzZcyB9-vVSYA5jBpuqYyiBK_TxSJfzdDh4ld0hDbxuwGns0ZC-533j-LXXGy5WoLCZRyDRPQAAfunXkIOEFZ7EgpwhNN0JxbBu-KBySvSA-v0hHfl31sROB2BR7FzUhtECA

###